### ISSUE TITLE
Não instala no Laravel 7

### ISSUE THREAD

**Issue by eumanito** [webmasterdro/paghiper-php-sdk#2]
Estou tentando instalar este pacote no Laravel 7, me retorna erro de dependência:

>   Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for webmasterdro/paghiper-php-sdk ^2.0.1 -> satisfiable by webmasterdro/paghiper-php-sdk[2.0.1].
>     - Can only install one of: guzzlehttp/guzzle[7.0.0, 6.5.x-dev].
>     - Can only install one of: guzzlehttp/guzzle[7.0.0-beta.1, 6.5.x-dev].
>     - Can only install one of: guzzlehttp/guzzle[7.0.0-beta.2, 6.5.x-dev].
>     - Can only install one of: guzzlehttp/guzzle[7.0.0-rc.1, 6.5.x-dev].
>     - Can only install one of: guzzlehttp/guzzle[7.0.1, 6.5.x-dev].
>     - Can only install one of: guzzlehttp/guzzle[7.0.x-dev, 6.5.x-dev].
>     - Can only install one of: guzzlehttp/guzzle[7.1.x-dev, 6.5.x-dev].
>     - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
>     - Conclusion: install guzzlehttp/guzzle 6.5.x-dev
>     - Installation request for guzzlehttp/guzzle ^7.0 -> satisfiable by guzzlehttp/guzzle[7.0.0, 7.0.0-beta.1, 7.0.0-beta.2, 7.0.0-rc.1, 7.0.1, 7.0.x-dev, 7.1.x-dev].

Tentei alterar o composer.json e também não funcionou. Aguma ideia?
> {
>  "require": {
>         "php": ">=5.6.0",
>         "guzzlehttp/guzzle": "^7.0"
>     },
> }

**Comment by pdrolima** [comment]
Olá,

Não presenciei esse conflito aqui. Como está o composer.json do seu projeto?

**Comment by eumanito** [comment]
Este pacote está compatível com laravel 7?

Meu composer.json
```
   "require": {
        "php": "^7.2.5",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^7.0",
        "laravel/framework": "^7.0",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^2.0",
        "laravelcollective/html": "^6.1",
    },
```

**Comment by pdrolima** [comment]
Olá, está compatível sim.

Mas eu vi que o Laravel está usando Guzzle na versão `ˆ6.3.` Você tem alguma necessidade específica para usar ele na versão 7?

**Comment by eumanito** [comment]
Obrigado Pedro, funcionou com o guzzle 6.3.

**Comment by pdrolima** [comment]
Show! =)

Qualquer coisa, pode entrar em contato.

Abs.

**Comment by eumanito** [comment]
Pedro, estou tendo problemas por manter o Guzzle na versão 6.3. Você poderia atualizar o pacote para o Guzzle 7?

O erro é "CSRF token mismatch." em rotas acionadas pelo axios/post

**Comment by pdrolima** [comment]
Olá,

O Laravel ainda utiliza o Guzzle 6.3. Você está enviando o XSRF-TOKEN com o axios? 

```
window.axios = require('axios');

window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';
```

**Comment by eumanito** [comment]
Quando coloco o Guzzle 6.3 até o Laravel faz downgrade (7.25.0 => 7.22.0), e o symfony também.

Pra resolver eu instalei esse pacote do Paghiper sem composer :(

**Comment by pdrolima** [comment]
Mas o erro de XSRF não tem relação com a versão do Guzzle. Eu até posso liberar com suporte a Guzzle 7, pelo que vi, o pacote não possui nenhum trecho de código que possa causar conflito, mas pelo que pude ver seu problema não é exatamente esse.

**Comment by pdrolima** [comment]
Liberei a versão 3.0 com suporte ao Guzzle 7, pode realizar o teste?

Assim que possível eu adiciono testes ao pacote.

**Comment by eumanito** [comment]
Pelo comando **composer require webmasterdro/paghiper-php-sdk:^3.0**
retorna: `Could not find package webmasterdro/paghiper-php-sdk in a version matching 3.0`

Colocando direto no composer funcionou.

Obrigado.

**Comment by pdrolima** [comment]
Por gentileza, me informe se a integração do PagHiper vai funcionar sem problemas na versão 3! =)

**Comment by eumanito** [comment]
Sim, está funcionando, já gerei boletos e consultei o status, tudo sem problemas.
